dist: trusty
sudo: required
language: node_js
addons:
   chrome: stable
branches:
  only:
    - master
matrix:
  include:
    # Local Browsers
    - node_js: 8
      env: KARMA=true KARMA_COVERAGE=true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run build
  - npm run test-ci
# - npm run e2e
notifications:
  email: false
deploy:
  provider: heroku
  api_key: d83958eb-c8aa-4d62-b657-9061aa416271
  strategy: git
