language: node_js
node_js:
  - stable
branches:
  only:
    - master
before_install:
  - npm i npm@^4 -g
install:
  - npm install
script:
  - npm run build
  - npm run test-ci
notifications:
  email: false
