dist: trusty
sudo: required
language: node_js
addons:
   chrome: stable
branches:
  only:
    - master
matrix:
  include:
    # Local Browsers
    - node_js: 8
      env: KARMA=true KARMA_COVERAGE=true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - webdriver-manager start
script:
  - npm run build
  - npm run test-ci
  - ionic-app-scripts serve & npm run e2e
notifications:
  email: false
deploy:
  provider: heroku
  api_key: ...
  strategy: git
