language: node_js
node_js:
  - stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - master
before_install:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
install:
  - npm install -g
script:
  - npm run test-ci
  - npm run ionic:serve & npm run e2e
  - npm run build
notifications:
  email: false
