language: node_js
node_js:
  - stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - master
before_install:
  - npm i npm@^4 -g
install:
  - npm install
script:
  - npm run build
  - npm run test-ci
  - npm run ionic:serve & npm run e2e
notifications:
  email: false
